window.ZonarConfig = {
  apiUrl: 'https://script.google.com/macros/s/AKfycbw8vu2lMM5WRrU7vK-p78rIlx5OKpgdm5_rnOyNVxiEFE_YhzPt2k2rnBq8p36AIpnx/exec',
  maps: [
    {
      id: 'PLANTA_BAJA',
      label: 'Planta Baja',
      src: 'assets/maps/planta-baja.png'
    },
    {
      id: 'PISO_1',
      label: 'Piso 1',
      src: 'assets/maps/piso-1.png'
    },
    {
      id: 'PISO_2',
      label: 'Piso 2',
      src: 'assets/maps/piso-2.png'
    },
    {
      id: 'PARQUEADERO_PB',
      label: 'Parqueadero PB',
      src: 'assets/maps/parqueadero-planta-baja.png'
    },
    {
      id: 'PARQUEADERO_SUBSUELO',
      label: 'Subsuelo',
      src: 'assets/maps/parqueadero-subsuelo.png'
    }
  ],
  knownLocations: [
    { codigo: 'L03', nombre: 'Local L03', piso: 'PLANTA_BAJA', tipo: 'LOCAL' },
    { codigo: 'L07', nombre: 'Local L07', piso: 'PLANTA_BAJA', tipo: 'LOCAL' },
    { codigo: 'L08', nombre: 'Local L08', piso: 'PLANTA_BAJA', tipo: 'LOCAL' },
    { codigo: 'L09', nombre: 'Local L09', piso: 'PLANTA_BAJA', tipo: 'LOCAL' },
    { codigo: 'L10', nombre: 'Local L10', piso: 'PLANTA_BAJA', tipo: 'LOCAL' },
    { codigo: 'L11', nombre: 'Local L11', piso: 'PLANTA_BAJA', tipo: 'LOCAL' },
    { codigo: 'L12', nombre: 'Local L12', piso: 'PLANTA_BAJA', tipo: 'LOCAL' },
    { codigo: 'L13', nombre: 'Local L13', piso: 'PLANTA_BAJA', tipo: 'LOCAL' },
    { codigo: 'L15', nombre: 'Local L15', piso: 'PLANTA_BAJA', tipo: 'LOCAL' },
    { codigo: 'L18', nombre: 'Local L18', piso: 'PLANTA_BAJA', tipo: 'LOCAL' },
    { codigo: 'EVENTOS', nombre: 'Zona de eventos', piso: 'PISO_1', tipo: 'ZONA' },
    { codigo: 'L100', nombre: 'Local L100', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L101', nombre: 'Local L101', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L102', nombre: 'Local L102', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L103', nombre: 'Local L103', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L111', nombre: 'Local L111', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L115', nombre: 'Local L115', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L116', nombre: 'Local L116', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L117', nombre: 'Local L117', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L118', nombre: 'Local L118', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L119', nombre: 'Local L119', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L120', nombre: 'Local L120', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L123', nombre: 'Local L123', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L125', nombre: 'Local L125', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L127', nombre: 'Local L127', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L128', nombre: 'Local L128', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L129', nombre: 'Local L129', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L130', nombre: 'Local L130', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L131', nombre: 'Local L131', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L132', nombre: 'Local L132', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L132A', nombre: 'Local L132A', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L133', nombre: 'Local L133', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L134', nombre: 'Local L134', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L135', nombre: 'Local L135', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L137', nombre: 'Local L137', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L139', nombre: 'Local L139', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L140', nombre: 'Local L140', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L141', nombre: 'Local L141', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L220', nombre: 'Local L220', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'L251', nombre: 'Local L251', piso: 'PISO_1', tipo: 'LOCAL' },
    { codigo: 'PATIO_COMIDAS', nombre: 'Patio de comidas', piso: 'PISO_2', tipo: 'ZONA' },
    { codigo: 'L200', nombre: 'Local L200', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L201', nombre: 'Local L201', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L202', nombre: 'Local L202', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L204', nombre: 'Local L204', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L205', nombre: 'Local L205', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L206', nombre: 'Local L206', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L207', nombre: 'Local L207', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L208', nombre: 'Local L208', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L209', nombre: 'Local L209', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L210', nombre: 'Local L210', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L211', nombre: 'Local L211', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L212', nombre: 'Local L212', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L213', nombre: 'Local L213', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L214', nombre: 'Local L214', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L215', nombre: 'Local L215', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L216', nombre: 'Local L216', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L217', nombre: 'Local L217', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L218', nombre: 'Local L218', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L219', nombre: 'Local L219', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L221', nombre: 'Local L221', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L222', nombre: 'Local L222', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L224', nombre: 'Local L224', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L225', nombre: 'Local L225', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L226', nombre: 'Local L226', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L227', nombre: 'Local L227', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L229', nombre: 'Local L229', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L230', nombre: 'Local L230', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L231', nombre: 'Local L231', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L232', nombre: 'Local L232', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L233A', nombre: 'Local L233A', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L234', nombre: 'Local L234', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L235', nombre: 'Local L235', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L236', nombre: 'Local L236', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L237', nombre: 'Local L237', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L238', nombre: 'Local L238', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L238A', nombre: 'Local L238A', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L239', nombre: 'Local L239', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L241', nombre: 'Local L241', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'L263', nombre: 'Local L263', piso: 'PISO_2', tipo: 'LOCAL' },
    { codigo: 'PARQUEADERO_PB', nombre: 'Parqueadero planta baja', piso: 'PARQUEADERO_PB', tipo: 'PARQUEADERO' },
    { codigo: 'PARQUEADERO_SUBSUELO', nombre: 'Parqueadero subsuelo', piso: 'PARQUEADERO_SUBSUELO', tipo: 'PARQUEADERO' },
    { codigo: 'S01', nombre: 'Local S01', piso: 'PARQUEADERO_SUBSUELO', tipo: 'LOCAL' },
    { codigo: 'S05', nombre: 'Local S05', piso: 'PARQUEADERO_SUBSUELO', tipo: 'LOCAL' },
    { codigo: 'S06', nombre: 'Local S06', piso: 'PARQUEADERO_SUBSUELO', tipo: 'LOCAL' },
    { codigo: 'S09', nombre: 'Local S09', piso: 'PARQUEADERO_SUBSUELO', tipo: 'LOCAL' }
  ]
};
