(function () {
  window.ZonarDirectoryDefaults = [
    { codigo: 'EVENTOS', nombre: 'Zona de eventos', categoria: 'Zonas comunes', piso: 'PISO_1', tipo: 'ZONA', activo: 'SI' },
    { codigo: 'PATIO_COMIDAS', nombre: 'Patio de comidas', categoria: 'Zonas comunes', piso: 'PISO_2', tipo: 'ZONA', activo: 'SI' },
    { codigo: 'PARQUEADERO_PB', nombre: 'Parqueadero planta baja', categoria: 'Parqueaderos', piso: 'PARQUEADERO_PB', tipo: 'PARQUEADERO', activo: 'SI' },
    { codigo: 'PARQUEADERO_SUBSUELO', nombre: 'Parqueadero subsuelo', categoria: 'Parqueaderos', piso: 'PARQUEADERO_SUBSUELO', tipo: 'PARQUEADERO', activo: 'SI' },

    { codigo: 'L204', nombre: 'RAME', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L212', nombre: 'EXPLORER', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L239', nombre: 'JEAN UP', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L215', nombre: 'LEX RACING', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L263', nombre: 'LILI PINK', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L225', nombre: 'MY DREAMS', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L221', nombre: 'OH STORE', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L207', nombre: 'PINTO', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L206', nombre: 'PONY STORE', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L205', nombre: 'ROY SPORTS', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L214', nombre: 'SOLE MIO', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L200', nombre: 'TELESHOP', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L222', nombre: 'VASARI MOZIONI', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L219', nombre: 'ZIZI', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L116', nombre: 'AZZARIA', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L127', nombre: 'CAPTOOS', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L141', nombre: 'DERICK', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L125', nombre: 'DUDES & BETTYS', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L115', nombre: 'LA PERCHA CLOTHING', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L131', nombre: 'LA CASA DEL JEAN', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L134', nombre: 'MARATHON SPORTS', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L137', nombre: 'PAYLESS', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L135', nombre: 'RM', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L101', nombre: 'ROLAND', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L120', nombre: 'TATY', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L111', nombre: 'TELA TINTA', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L123', nombre: 'TOTTO', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L113', nombre: 'UOMO VENETTO', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L118', nombre: 'VATEX', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L129', nombre: 'KOAJ', categoria: 'Moda, calzado y ropa deportiva', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L18', nombre: 'RM', categoria: 'Moda, calzado y ropa deportiva', piso: 'PLANTA_BAJA', tipo: 'LOCAL', activo: 'SI' },

    { codigo: 'L226', nombre: 'BANCO DEL AUSTRO', categoria: 'Servicios varios', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L217', nombre: 'CLARO', categoria: 'Servicios varios', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L213', nombre: 'MUTUALISTA IMBABURA', categoria: 'Servicios varios', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L132', nombre: 'BANCO DEL PICHINCHA', categoria: 'Servicios varios', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L133', nombre: 'MOVISTAR', categoria: 'Servicios varios', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L13', nombre: 'BANCO PROCREDIT', categoria: 'Servicios varios', piso: 'PLANTA_BAJA', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L15', nombre: 'MARTINIZING', categoria: 'Servicios varios', piso: 'PLANTA_BAJA', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L12', nombre: 'SPLASH CAR', categoria: 'Servicios varios', piso: 'PLANTA_BAJA', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'S06', nombre: 'LA FAN FM', categoria: 'Servicios varios', piso: 'PARQUEADERO_SUBSUELO', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'S09', nombre: 'PSN INTERNATIONAL', categoria: 'Servicios varios', piso: 'PARQUEADERO_SUBSUELO', tipo: 'LOCAL', activo: 'SI' },

    { codigo: 'L209', nombre: 'LINEA NUEVA MOBILIARIO', categoria: 'Hogar y decoracion', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L103', nombre: 'MACHLER', categoria: 'Hogar y decoracion', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L119', nombre: 'RESIFLEX', categoria: 'Hogar y decoracion', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L11', nombre: 'HOME VEGA', categoria: 'Hogar y decoracion', piso: 'PLANTA_BAJA', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L03', nombre: 'PYCCA', categoria: 'Hogar y decoracion', piso: 'PLANTA_BAJA', tipo: 'LOCAL', activo: 'SI' },

    { codigo: 'L238', nombre: 'GELATO POP', categoria: 'Cafeterias y heladerias', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L202', nombre: 'LA DULCERIA', categoria: 'Cafeterias y heladerias', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L238A', nombre: 'TUTTO FREDDO', categoria: 'Cafeterias y heladerias', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L220', nombre: 'LOS ALPES HELADERIA', categoria: 'Cafeterias y heladerias', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L132A', nombre: 'SWEET & COFFEE', categoria: 'Cafeterias y heladerias', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L09', nombre: 'PANADERIA NUESTRA TRADICION', categoria: 'Cafeterias y heladerias', piso: 'PLANTA_BAJA', tipo: 'LOCAL', activo: 'SI' },

    { codigo: '26', nombre: 'ACUARELAS DE SUENOS', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '22', nombre: 'CELL HOUSE', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '24', nombre: 'CHURROS 593', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '32', nombre: 'CREPUSCULO', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '33', nombre: 'FELICIA ACCESORIOS', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '36', nombre: 'JOYAS JF', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '34', nombre: 'LAS DE OSMA EMPANADAS', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '27', nombre: 'LOS ALPES HELADERIA', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '35', nombre: 'MOTO AVENTURA', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '31', nombre: 'PANKKO SUSHI CON TENDENCIA', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '29', nombre: 'SMOOTHIE', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '30', nombre: 'ICE SWEET', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '25', nombre: 'SWEET OBLEA', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '28', nombre: 'THAIS JOYAS', categoria: 'Islas', piso: 'PISO_2', tipo: 'ISLA', activo: 'SI' },
    { codigo: '19', nombre: 'ANIMAL ADVENTURE', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '15', nombre: 'ATM BANCO DEL PACIFICO', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '12', nombre: 'BUBBLE TEA', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '04', nombre: 'COCO EXPRESS', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '09', nombre: 'CLARO', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '13', nombre: 'CHIKY PLAYA', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '16', nombre: 'SKIN CARE', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '11', nombre: 'JUGUETRON', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '22', nombre: 'MANGO & FRESA', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '06', nombre: 'MIELISSIMO', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '07', nombre: 'NETLIFE', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '20', nombre: 'PERFUMES FACTORY', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '05', nombre: 'PLATART', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '21', nombre: 'PSN INTERNACIONAL', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '08', nombre: 'PUNTO DE LA SUERTE', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '18', nombre: 'SHIATSU EXPRESS', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '10', nombre: 'SMART SECONDS', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '17', nombre: 'SPORTBET', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '14', nombre: 'VLYN SHOP', categoria: 'Islas', piso: 'PISO_1', tipo: 'ISLA', activo: 'SI' },
    { codigo: '01', nombre: 'AMORE MIO', categoria: 'Islas', piso: 'PLANTA_BAJA', tipo: 'ISLA', activo: 'SI' },
    { codigo: '03', nombre: 'KFC POSTRES', categoria: 'Islas', piso: 'PLANTA_BAJA', tipo: 'ISLA', activo: 'SI' },
    { codigo: '02', nombre: 'TUENTI', categoria: 'Islas', piso: 'PLANTA_BAJA', tipo: 'ISLA', activo: 'SI' },

    { codigo: 'L224', nombre: 'PEKE KIDS', categoria: 'Entretenimiento', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L201', nombre: 'STARCINES', categoria: 'Entretenimiento', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L211', nombre: 'STAR GAMES', categoria: 'Entretenimiento', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L102', nombre: 'MEGA SANTA MARIA', categoria: 'Supermercado', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },

    { codigo: 'L232', nombre: 'AMERICAN DELI', categoria: 'Restaurantes, postres y comidas', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L236', nombre: 'BUFF STEAK HOUSE', categoria: 'Restaurantes, postres y comidas', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L229', nombre: 'CAMARON REVENTADO', categoria: 'Restaurantes, postres y comidas', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L235', nombre: 'CEVICHES DE LA RUMINAHUI', categoria: 'Restaurantes, postres y comidas', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L234', nombre: 'CHIFA IMPERIO', categoria: 'Restaurantes, postres y comidas', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L228', nombre: 'KFC', categoria: 'Restaurantes, postres y comidas', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L233A', nombre: 'LA SANDUCHERIA', categoria: 'Restaurantes, postres y comidas', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L210', nombre: 'LA TABLITA DEL TARTARO', categoria: 'Restaurantes, postres y comidas', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L230', nombre: 'MENESTRAS DEL NEGRO', categoria: 'Restaurantes, postres y comidas', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L237', nombre: 'QUIHUBO PUES SAZON Y LENA', categoria: 'Restaurantes, postres y comidas', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L231', nombre: 'TROPI BURGUER', categoria: 'Restaurantes, postres y comidas', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L10', nombre: 'PIZZA HUT', categoria: 'Restaurantes, postres y comidas', piso: 'PLANTA_BAJA', tipo: 'LOCAL', activo: 'SI' },

    { codigo: 'L208', nombre: 'GLORIA SALTOS', categoria: 'Salud, belleza y farmacias', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L251', nombre: 'DMUJERES', categoria: 'Salud, belleza y farmacias', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L117', nombre: 'FYBECA', categoria: 'Salud, belleza y farmacias', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L140', nombre: 'MARIA GRACIA PELUQUERIA', categoria: 'Salud, belleza y farmacias', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L08', nombre: 'PHARMACYS', categoria: 'Salud, belleza y farmacias', piso: 'PLANTA_BAJA', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'S05', nombre: 'REDUX CLINICA DE LA BELLEZA', categoria: 'Salud, belleza y farmacias', piso: 'PARQUEADERO_SUBSUELO', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'S01', nombre: 'REDUX CLINICA DE LA BELLEZA', categoria: 'Salud, belleza y farmacias', piso: 'PARQUEADERO_SUBSUELO', tipo: 'LOCAL', activo: 'SI' },

    { codigo: 'L100', nombre: 'ALMACENES JAPON', categoria: 'Tecnologia y electrodomesticos', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L07', nombre: 'CELL TECH', categoria: 'Tecnologia y electrodomesticos', piso: 'PLANTA_BAJA', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L241', nombre: 'JOYAS ESMERALDA', categoria: 'Opticas, joyas y accesorios', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L216', nombre: 'TIEMPO DE ORO', categoria: 'Opticas, joyas y accesorios', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L128', nombre: 'OPTICAS GMO', categoria: 'Opticas, joyas y accesorios', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L139', nombre: 'OPTICA LOS ANDES', categoria: 'Opticas, joyas y accesorios', piso: 'PISO_1', tipo: 'LOCAL', activo: 'SI' },
    { codigo: 'L218', nombre: "BOOK'S STORE", categoria: 'Librerias', piso: 'PISO_2', tipo: 'LOCAL', activo: 'SI' }
  ];
}());
